loadbalancer:
  build: .
  dockerfile: Dockerfile
  ports:
    - "5000:5000"
  links:
    - "mongodb:mongodb"
    - "redis:redis"
  environment:
    - REDIS_HOST=redis
    - REDIS_PORT=6379
    - REDIS_PASSWORD=mypass
    - MONGO_HOST=mongodb
    - MONGO_PORT=27017
    - MONGO_USERNAME=user
    - MONGO_PASSWORD=mypass
    - MONGO_DATABASE=mydatabase

mongodb:
  image: tutum/mongodb
  ports:
    - "27017:27017"
  environment:
    - MONGODB_USER=user
    - MONGODB_PASS=mypass
    - MONGODB_DATABASE=mydatabase

redis:
  image: tutum/redis
  ports:
    - "6379:6379"
  environment:
    - REDIS_PASS=mypass

